version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      build-dependencies:
        applies-to: version-updates
        patterns:
          - '@types/*'
          - 'typescript'
          - 'esbuild'
        update-types:
          - major
          - minor
          - patch
